services:
  # ── Base de datos ──
  postgres-users:
    container_name: DB-users
    image: postgres:16-alpine
    restart: on-failure
    env_file: .env
    environment:
      POSTGRES_DB: ${USER_DB_NAME}
      POSTGRES_USER: ${USER_DB_USER}
      POSTGRES_PASSWORD: ${USER_DB_PASSWORD}
    volumes:
      - pg_users_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${USER_DB_USER} -d ${USER_DB_NAME}"]
      interval: 5s
      retries: 5


  postges-org:
    container_name: DB-organizations
    image: postgres:16-alpine
    restart: on-failure
    env_file: .env
    environment:
      POSTGRES_DB: ${ORG_DB_NAME}
      POSTGRES_USER: ${ORG_DB_USER}
      POSTGRES_PASSWORD: ${ORG_DB_PASSWORD}
    volumes:
      - pg_org_data:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${ORG_DB_USER} -d ${ORG_DB_NAME}"]
      interval: 5s
      retries: 5


  postgres-tickets:
    container_name: DB-tickets
    image: postgres:16-alpine
    restart: on-failure
    env_file: .env
    environment:
      POSTGRES_DB: ${TICKET_DB_NAME}
      POSTGRES_USER: ${TICKET_DB_USER}
      POSTGRES_PASSWORD: ${TICKET_DB_PASSWORD}
    volumes:
      - pg_tickets_data:/var/lib/postgresql/data
    ports:
      - "5435:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${TICKET_DB_USER} -d ${TICKET_DB_NAME}"]
      interval: 5s
      retries: 5


  postgres-agent:
    container_name: DB-agent
    image: postgres:16-alpine
    restart: on-failure
    env_file: .env
    environment:
      POSTGRES_DB: ${AGENT_DB_NAME}
      POSTGRES_USER: ${AGENT_DB_USER}
      POSTGRES_PASSWORD: ${AGENT_DB_PASSWORD}
    volumes:
      - pg_agent_data:/var/lib/postgresql/data
    ports:
      - "5436:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${AGENT_DB_USER} -d ${AGENT_DB_NAME}"]
      interval: 5s
      retries: 5


  qdrant:
    container_name: qdrant
    image: qdrant/qdrant:latest
    restart: unless-stopped
    volumes:
      - qdrant_data:/qdrant/storage
    ports:
      - "6333:6333"
      - "6334:6334"


  # ── Servicios ──
  api-gateway:
    container_name: api-gateway
    build: ./api-gateway
    restart: on-failure
    env_file: .env
    environment:
      AUTH_SERVICE_URL: ${AUTH_SERVICE_URL}
      TICKET_SERVICE_URL: ${TICKET_SERVICE_URL}
      NOTIFICATION_SERVICE_URL: ${NOTIFICATION_SERVICE_URL}
      AGENT_SERVICE_URL: ${AGENT_SERVICE_URL}
      REDIS_URL: ${REDIS_URL}
    ports:
      - "3000:8000"   # frontend calls http://localhost:3000/api
    depends_on:
      - redis
      - rabbitmq
      - auth-service
      - ticket-service
      - agent-service


  auth-service:
    container_name: auth-service
    build: ./auth-service
    restart: on-failure
    env_file: .env
    environment:
      DATABASE_URL: ${USER_DB_URL}
      DATABASE_URL_ORG: ${ORG_DB_URL}
      REDIS_URL: ${REDIS_URL}
    ports:
      - "8001:8001"
    depends_on:
      - postgres-users
      - redis


  ticket-service:
    container_name: ticket-service
    build: ./ticket-service
    restart: on-failure
    env_file: .env
    environment:
      DATABASE_URL: ${TICKET_DB_URL}
      AGENT_SERVICE_URL: ${AGENT_SERVICE_URL}
    ports:
      - "8002:8002"
    depends_on:
      - postgres-tickets


  notification-service:
    container_name: notification-service
    build: ./notification-service
    restart: on-failure
    env_file: .env
    environment:
      DATABASE_URL: ${TICKET_DB_URL}
      RABBITMQ_URL: ${RABBITMQ_URL}
    ports:
      - "8003:8003"
    depends_on:
      - rabbitmq
      - postgres-tickets


  agent-service:
    container_name: agent-service
    build: ./agent-service
    restart: on-failure
    env_file: .env
    environment:
      DATABASE_URL: ${AGENT_DB_URL}
      QDRANT_URL: http://qdrant:6333
      TICKET_SERVICE_URL: ${TICKET_SERVICE_URL}
    ports:
      - "8004:8004"
    depends_on:
      - postgres-agent
      - qdrant
      - ticket-service



  # ── Herramientas ──
  redis:
    container_name: Redis
    image: redis:7-alpine
    restart: on-failure
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      retries: 5


  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.13-management
    restart: on-failure
    env_file: .env
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    ports:
      - "5672:5672"     # comunicación entre servicios
      - "15672:15672"   # panel web
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5



volumes:
  pg_users_data:
  pg_org_data:
  pg_tickets_data:
  pg_agent_data:

  qdrant_data:
  rabbitmq_data:
  